[lite]
gist = "c9efdd860fe031887c948ecc6cf27a5a"

[repos]
lumino.github.merge_with = ["pull/655"]
ipywidgets.github.merge_with = ["pull/3847"]

[repos.jupyterlab.github]
merge_strategy = "ort"
merge_options = ["theirs"]
merge_with = [
  "pull/15443",
  "pull/15347"
]
