#:schema ./docs/_static/jupyak-v0.schema.json

[lite]
gist = "60d9f604bdf00715e3d25f6436f8751f"

[repos.ipywidgets.github]
merge_with = [
  "pull/3847",
]

[repos.jupyterlite.github]
merge_strategy = "ort"
# (un)comment the below to (un)break the build
merge_options = ["theirs"]
merge_with = [
  "pull/1263",
]

[repos.jupyterlite.js]
link_exclude_patterns = [
  "^@jupyterlab/(debugger(-extension)?|extensionmanager(-extension)?|hub-extension|nbconvert-css|pluginmanager-extension|terminal(-extension)?|template)$",
  "^@jupyter-notebook/(documentsearch-extension|lab-extension|terminal-extension)$",
]

[repos.jupyterlite.js.patch_package_jsons."app/lab"]
dependencies = { "@jupyterlab/celltags-extension" = "*" }
