name: badges
on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = context.issue.number;
            const {repo, owner} = context.repo;
            const body = `[![jupyak-badge](https://jupyak.rtfd.io/en/latest/_static/img/badge.svg)](https://jupyak--${issue_number}.org.readthedocs.build/en/${issue_number}) :point_left: Try it on ReadTheDocs`;
            github.rest.issues.createComment({issue_number, owner, repo, body});
