name: self

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  JPYK_ALLOW_NO_CONFIG: 1
  CACHE_EPOCH: 0

jobs:
  self:
    name: self
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: .github/conda-linux-64.lock
          miniforge-variant: Mambaforge
          use-mamba: true
      - run: doit bootstrap
      - uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: '**/node_modules'
          key: |
            ${{ env.CACHE_EPOCH }}-node_modules-${{ hashFiles('yarn.lock', '.github/conda-linux-64.lock') }}
      - run: doit self:js:*
      - run: doit self:schema:*
      - run: doit self:build:*
      - run: doit self:test:*
      - run: doit self:docs:*
